### ISSUE TITLE
[XL-5] v1.0 Sprint

### ISSUE THREAD

**Issue by XL19860214** [Xuwei-Li/xuwei.li#5]
# 0. [v1.0] Sprint
* [x] 1. [v1.0] Project Management 项目管理 #1 
* [x] 2. [v1.0] Business Strategy 商业策略 #2
* [x] 3. [v1.0] Product Roadmap 产品轨迹 #3
* [x] 4. [v1.0] Architecture Design 架构设计 #4
* [x] 5. Requirements prototype 需求原型 https://dmv1c8.axshare.com/
* [ ] 6. Theme style 主题样式 https://dribbble.com/Xuwei-Li
* [ ] 7. Homepage 网站主页
* [ ] 8. Landing pages 登陆页面
* [ ] 9. Endless load more 无限内容
* [ ] 10. Business startup 商务启航

# 6. Theme style
* [ ] 6.1. Classify the brand, the web application and features
* [ ] 6.2. Answer to options
* [ ] 6.3. Color palette
* [ ] 6.4. Fonts
* [ ] 6.5. Images
* [ ] 6.6. Define elements
* [ ] 6.7. Construct layouts
* [ ] 6.8. Compose pages

# 7. Homepage
* [ ] 7.1. Page header
* [ ] 7.2. Desktop pixel advertising #6 
* [ ] 7.3. Main content
* [ ] 7.4. Page footer

## 7.1. Page header
* [ ] 7.1.1. Logo
* [ ] 7.1.2. Header navigation
* [ ] 7.1.3. User authentication

# 8. Landing pages
* [ ] 8.1. Making money 赚钱
* [ ] 8.2. Loving sex 性爱
* [ ] 8.3. Exploring adventure 探险
* [ ] 8.4. Perfecting life 完美人生

# 101. Links
* 101.1. https://dribbble.com/search/website
* 101.2. https://wordpress.org/themes/

## 101.2. https://wordpress.org/themes/
* 101.2.1. https://themeforest.net/popular_item/by_category?category=wordpress
* 101.2.2. https://www.templatemonster.com/wordpress-themes.php
* 101.2.3. https://underscores.me/

### 101.2.3. https://underscores.me/
* https://github.com/Automattic/_s
